name: Release

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: 'ubuntu-latest'
    env:
      GITHUB_TOKEN: ${{ secrets.TURING_SEGMENT_DOWNLOAD_MODELING_RELEASE }}
      GIT_TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Download release from private repository
        run: python scripts/release.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: assets/*

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: assets/*
